general {
    hide_cursor = false
}

background {
    monitor =
    color = rgba(303446ff)
}

input-field {
    monitor =
    size = 360, 64
    outline_thickness = 3
    dots_size = 0.22
    dots_spacing = 0.28
    outer_color = rgba(ca9ee6ff)
    inner_color = rgba(414559ff)
    font_color = rgba(c6d0f5ff)
    fail_color = rgba(e78284ff)
    check_color = rgba(a6d189ff)
    fade_on_empty = false
    placeholder_text = Password
    position = 0, 0
    halign = center
    valign = center
}
