general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 700
}

background {
    monitor =
    path = ~/Изображения/Wallpapers/deep-morning-minimal.jpg
    blur_passes = 2
    blur_size = 5
    brightness = 0.48
    vibrancy = 0.18
    color = rgba(191724ff)
}

animations {
    enabled = false
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(c6d0f5ff)
    font_size = 108
    font_family = JetBrainsMono Nerd Font
    position = 0, 350
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] LC_TIME=ru_RU.UTF-8 date +"%A, %d %B"
    color = rgba(b5bfe2ff)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 260
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:900000] ~/.local/bin/hypr-weather lock
    color = rgba(81c8beff)
    font_size = 24
    font_family = JetBrainsMono Nerd Font
    position = 0, 195
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 420, 66
    outline_thickness = 3
    dots_size = 0.22
    dots_spacing = 0.28
    dots_center = true
    outer_color = rgba(ca9ee6ff)
    inner_color = rgba(303446dd)
    font_color = rgba(c6d0f5ff)
    fail_color = rgba(e78284ff)
    check_color = rgba(a6d189ff)
    fade_on_empty = false
    placeholder_text = <span foreground="##b5bfe2">Введите пароль</span>
    fail_text = Неверный пароль
    rounding = 18
    position = 0, 45
    halign = center
    valign = center
}

label {
    monitor =
    text = Hyprland
    color = rgba(838ba7ff)
    font_size = 15
    font_family = JetBrainsMono Nerd Font
    position = 0, -25
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:3600000] ~/.local/bin/hypr-calendar lock
    color = rgba(c6d0f5ff)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -280
    halign = center
    valign = center
}
