$base = rgb(303446)
$mantle = rgb(292c3c)
$crust = rgb(232634)
$surface0 = rgb(414559)
$surface1 = rgb(51576d)
$surface2 = rgb(626880)
$overlay0 = rgb(737994)
$overlay1 = rgb(838ba7)
$text = rgb(c6d0f5)
$subtext = rgb(b5bfe2)
$mauve = rgb(ca9ee6)
$lavender = rgb(babbf1)
$teal = rgb(81c8be)
$peach = rgb(ef9f76)
$activeBorder = rgba(ca9ee6ee) rgba(81c8beee) 45deg
$inactiveBorder = rgba(626880aa)
$shadowColor = rgba(11111bdd)

