$base = rgb(eff1f5)
$mantle = rgb(e6e9ef)
$crust = rgb(dce0e8)
$surface0 = rgb(ccd0da)
$surface1 = rgb(bcc0cc)
$surface2 = rgb(acb0be)
$overlay0 = rgb(9ca0b0)
$overlay1 = rgb(8c8fa1)
$text = rgb(4c4f69)
$subtext = rgb(5c5f77)
$mauve = rgb(8839ef)
$lavender = rgb(7287fd)
$teal = rgb(179299)
$peach = rgb(fe640b)
$activeBorder = rgba(8839efee) rgba(179299ee) 45deg
$inactiveBorder = rgba(acb0beaa)
$shadowColor = rgba(4c4f6944)

